import { slugify } from "../lib/utils";
import type { Locale } from "./content";

export const STATUSES = ["works", "partial", "broken", "untested"] as const;
export type Status = (typeof STATUSES)[number];
export type Mod = { name: string; status: Status; note?: Record<Locale, string> };
const works = (name: string): Mod => ({ name, status: "works" });

export const MODS: Mod[] = [
    works("Advanced AE"),
    works("AE Infinity Booster"),
    works("AE2 Import Export Card"),
    works("AE2 Network Analyzer"),
    works("AE2 Wireless Terminals"),
    works("Aether II"),
    works("Agritech: Evolved"),
    works("AllTheCompressed"),
    works("AllTheModium"),
    works("AllTheOres"),
    works("AllTheTweaks"),
    works("Apotheosis"),
    works("Apothic Attributes"),
    works("Apothic Enchanting"),
    works("Apothic Spawners"),
    works("Applied Construction Sticks"),
    works("Applied Energistics 2"),
    works("Aquaculture 2"),
    works("Architectury"),
    works("Artifacts"),
    works("Atlas API"),
    works("AttributeFix"),
    works("Auroral"),
    works("Balm"),
    works("Baubley Heart Canisters"),
    works("BBL Core"),
    works("BBL Routers"),
    works("BBL Strainers"),
    works("Better Advanced Tooltips"),
    works("Better Advancements"),
    works("Better Compatibility Checker"),
    works("Building Gadgets 2"),
    works("Cable Tiers"),
    works("Camol"),
    works("Charging Gadgets"),
    works("Chisel"),
    works("Chunk Loaders"),
    works("Classic Pipes"),
    works("Clean Swing"),
    works("Clickable Advancements"),
    works("Cloth Config"),
    works("Clumps"),
    works("Cobblegen Galore"),
    works("Comforts"),
    works("Common Capabilities"),
    works("Configured"),
    works("Construction Sticks"),
    works("Cooking for Blockheads"),
    works("Copper Hopper"),
    works("Crafting on a Stick"),
    works("Crafting Tweaks"),
    works("Crash Utilities"),
    works("CraterLib"),
    works("Cristel Lib"),
    works("Croptopia"),
    works("Crystalix"),
    works("CTM"),
    works("Cucumber"),
    works("Cupboard"),
    works("Curios API"),
    works("Cyclops Core"),
    works("DeepNull Reforged"),
    works("Deimos"),
    works("DimStorage"),
    works("Dungeon Crawl"),
    works("Easy Piglins"),
    works("Easy Villagers"),
    works("EdivadLib"),
    works("Elevator Mod"),
    works("Enchantment Descriptions"),
    works("Ender IO"),
    works("Ender IO Endergy"),
    works("Energized Power"),
    works("Energy Meter"),
    works("Entangled"),
    works("EpheroLib"),
    works("Epitaphs"),
    works("EvilCraft"),
    works("Ex Deorum"),
    works("Explorer's Compass"),
    works("Extended AE"),
    works("Extended Crafting"),
    works("Extra Disks"),
    works("Extreme Sound Muffler"),
    works("FancyMenu"),
    works("Farming for Blockheads"),
    works("Fast Noise"),
    works("Fast Suite"),
    works("FastFurnace"),
    works("FastWorkbench"),
    works("Ferrite Core"),
    works("Forbidden Arcanus"),
    works("Forge Config API Port"),
    works("FramedBlocks"),
    works("Framework"),
    works("FTB Chunks"),
    works("FTB Essentials"),
    works("FTB Filter System"),
    works("FTB Library"),
    works("FTB Quests"),
    works("FTB Ranks"),
    works("FTB Teams"),
    works("FTB Ultimine"),
    works("FTB XMod Compat"),
    works("Functional Storage"),
    works("Gateways To Eternity"),
    works("GeckoLib"),
    works("Generator Galore"),
    works("GeOre"),
    works("Get It Together, Drops!"),
    works("Glodium"),
    works("GuideME"),
    works("Ice and Fire Community Edition"),
    works("imfast"),
    works("In World Recipes"),
    works("Integrated Crafting"),
    works("Integrated Dynamics"),
    works("Integrated Terminals"),
    works("Integrated Tunnels"),
    works("Interdimensional Wireless Transmitter"),
    works("Inventory Essentials"),
    works("Iron Furnaces"),
    works("Iron Jetpacks"),
    works("Iron's Arms 'n Artifice"),
    works("Iron's Gems 'n Jewelry"),
    works("Iron's Lib"),
    works("Item Collectors"),
    works("Jade"),
    works("Jonn's Trophies"),
    works("Journeymap"),
    works("Jumpy Boats"),
    works("Jupiter"),
    works("Just Dire Things"),
    works("Just Enough Archaeology"),
    works("Just Enough Items"),
    works("Just Enough Professions"),
    works("Just Enough Recipe Sharing"),
    works("Just Hammers"),
    works("Konkrete"),
    works("KubeJS"),
    works("Laser Bridges"),
    works("LaserIO"),
    works("Lithostitched"),
    works("LogisticsNetworks"),
    works("LootR"),
    works("Luminax"),
    works("Macaw's Bridges"),
    works("Macaw's Doors"),
    works("Macaw's Fences and Walls"),
    works("Macaw's Furniture"),
    works("Macaw's Lights and Lamps"),
    works("Macaw's Paths and Pavings"),
    works("Macaw's Roofs"),
    works("Macaw's Stairs and Balconies"),
    works("Macaw's Trapdoors"),
    works("Macaw's Windows"),
    works("Mahou Tsukai"),
    works("Mapple"),
    works("MaxHealthFix"),
    works("Measurements"),
    works("Melody"),
    works("Mining Gadgets"),
    works("ModernFix"),
    works("Modonomicon"),
    works("Modular Force Field System"),
    works("Modular Routers"),
    works("More Dragon Eggs"),
    works("More Red"),
    works("MrCrayfish's Furniture Mod: Refurbished"),
    works("Mystical Agradditions"),
    works("Mystical Agriculture"),
    works("Mystical Agriculture Tiered Crystals"),
    works("Mystical Automation"),
    works("Mystical Customization"),
    works("Nature's Compass"),
    works("NeoVitae"),
    works("NetherPortalFix"),
    works("No Chat Reports"),
    works("No More Craters"),
    works("Occultism"),
    works("Oritech"),
    works("Overstress"),
    works("Pipe Connector"),
    works("Pipez"),
    works("Placebo"),
    works("Powah"),
    works("Productive Bees"),
    works("Productive Farming"),
    works("Productive Metalworks"),
    works("Productive Trees"),
    works("Pylons"),
    works("QuarryPlus"),
    {
        name: "Railcraft Reborn",
        status: "broken",
        note: {
            fr: "Crash serveur. Bug de Leafs sur les game events, pas de Railcraft.",
            en: "Server crash. Leafs bug on game events, not Railcraft's."
        }
    },
    works("Refined Construction Sticks"),
    works("Refined Fluid Substitution"),
    works("Refined Storage"),
    works("Refined Storage Curios Integration"),
    works("Refined Storage JEI Integration"),
    works("Refined Storage Quartz Arsenal"),
    works("Refined Types"),
    works("Regions Unexplored"),
    works("Reliquary Reincarnations"),
    works("Rhino"),
    works("Roots Classic"),
    works("Scalable Cats Force"),
    works("ScalableLux"),
    works("Searchables"),
    works("Shogi"),
    works("Silent Gear"),
    works("Silent Gear Metalworks"),
    works("Silent Lib"),
    works("Silent's Gems"),
    works("Simple Backups"),
    works("Simple Magnets"),
    works("Sophisticated Backpacks"),
    works("Sophisticated Core"),
    works("Sophisticated Storage"),
    works("Sophisticated Storage In Motion"),
    works("Spark"),
    works("Spice of Life: Carrot Edition"),
    works("Spider Overhaul"),
    works("Step Crafter"),
    works("Super Factory Manager"),
    works("Tectonic"),
    works("Terralith"),
    works("The Undergarden"),
    works("Theurgy"),
    works("Theurgy KubeJS"),
    works("Titanium"),
    works("Tool Belt"),
    works("Training Dummy"),
    works("Transmog"),
    works("Trash Cans"),
    works("TrashSlot"),
    works("Underground Villages"),
    works("Underwater Village"),
    works("Universal Grid"),
    works("Uranus"),
    works("Utilitarian"),
    works("Valhelsia Core"),
    works("Waystones"),
    works("Wither Skeleton Tweaks"),
    works("Wits")
];

export const searchMods = (query: string): Mod[] => MODS.filter((mod) => slugify(mod.name).includes(slugify(query)));
