import { slugify } from "../lib/utils";
import type { Locale } from "./content";

export const STATUSES = ["works", "partial", "broken", "untested"] as const;
export type Status = (typeof STATUSES)[number];
export type Mod = { name: string; status: Status; note?: Record<Locale, string> };
const works = (name: string): Mod => ({ name, status: "works" });
const untested = (name: string): Mod => ({ name, status: "untested" });

const TESTED: Mod[] = [
    works("Advanced AE"),
    works("Apotheosis"),
    works("Apothic Attributes"),
    works("Apothic Enchanting"),
    works("Apothic Spawners"),
    works("Applied Energistics 2"),
    works("Architectury"),
    works("AttributeFix"),
    works("Balm"),
    works("Chunk Loaders"),
    works("Clumps"),
    works("Common Capabilities"),
    works("Construction Sticks"),
    works("Copper Hopper"),
    works("Cyclops Core"),
    works("Easy Villagers"),
    works("Ender IO"),
    works("Entangled"),
    works("Ex Deorum"),
    works("Explorer's Compass"),
    works("Extended AE"),
    works("Extended Crafting"),
    works("FastWorkbench"),
    works("Integrated Dynamics"),
    works("Iron Furnaces"),
    works("Iron Jetpacks"),
    works("Item Collectors"),
    works("Just Hammers"),
    {
        name: "LootR",
        status: "partial",
        note: {
            fr: "Se charge et ne cause aucun souci en jeu, mais ne fonctionne pas : les coffres restent ceux de vanilla.",
            en: "Loads and causes no issue in game, but does not work: chests stay the vanilla ones."
        }
    },
    works("Mahou Tsukai"),
    works("ModernFix"),
    works("Modonomicon"),
    works("Modular Routers"),
    works("Mystical Agriculture"),
    works("Nature's Compass"),
    works("NeoVitae"),
    works("Oritech"),
    works("Pipez"),
    works("Powah"),
    works("Pylons"),
    works("Refined Storage"),
    works("Sophisticated Backpacks"),
    works("Sophisticated Core"),
    works("Sophisticated Storage"),
    works("Trash Cans")
];

const UNTESTED: Mod[] = [
    untested("AE2 Import Export Card"),
    untested("AE2 Network Analyzer"),
    untested("AE Infinity Booster"),
    untested("Aether II"),
    untested("Agritech: Evolved"),
    untested("AllTheCompressed"),
    untested("AllTheModium"),
    untested("AllTheOres"),
    untested("AllTheTweaks"),
    untested("Applied Construction Sticks"),
    untested("Aquaculture 2"),
    untested("Artifacts"),
    untested("Atlas API"),
    untested("Auroral"),
    untested("Baubley Heart Canisters"),
    untested("BBL Core"),
    untested("BBL Routers"),
    untested("BBL Strainers"),
    untested("Better Advanced Tooltips"),
    untested("Better Compatibility Checker"),
    untested("Building Gadgets 2"),
    untested("Cable Tiers"),
    untested("Camol"),
    untested("Charging Gadgets"),
    untested("Chisel"),
    untested("Classic Pipes"),
    untested("Clean Swing"),
    untested("Clickable Advancements"),
    untested("Cobblegen Galore"),
    untested("Comforts"),
    untested("Configured"),
    untested("Cooking for Blockheads"),
    untested("Crafting on a Stick"),
    untested("Crafting Tweaks"),
    untested("Crash Utilities"),
    untested("CraterLib"),
    untested("Cristel Lib"),
    untested("Croptopia"),
    untested("Crystalix"),
    untested("CTM"),
    untested("Cupboard"),
    untested("Curios API"),
    untested("DeepNull Reforged"),
    untested("Deimos"),
    untested("DimStorage"),
    untested("Dungeon Crawl"),
    untested("Easy Piglins"),
    untested("EdivadLib"),
    untested("Elevator Mod"),
    untested("Enchantment Descriptions"),
    untested("Ender IO Endergy"),
    untested("Energized Power"),
    untested("Energy Meter"),
    untested("EpheroLib"),
    untested("Epitaphs"),
    untested("EvilCraft"),
    untested("Extra Disks"),
    untested("Extreme Sound Muffler"),
    untested("FancyMenu"),
    untested("Farming for Blockheads"),
    untested("FastFurnace"),
    untested("Fast Suite"),
    untested("Forbidden Arcanus"),
    untested("Forge Config API Port"),
    untested("FramedBlocks"),
    untested("Framework"),
    untested("FTB Chunks"),
    untested("FTB Essentials"),
    untested("FTB Filter System"),
    untested("FTB Library"),
    untested("FTB Quests"),
    untested("FTB Ranks"),
    untested("FTB Teams"),
    untested("FTB Ultimine"),
    untested("FTB XMod Compat"),
    untested("Functional Storage"),
    untested("Gateways To Eternity"),
    untested("Generator Galore"),
    untested("GeOre"),
    untested("Get It Together, Drops!"),
    untested("Ice and Fire Community Edition"),
    untested("imfast"),
    untested("Integrated Crafting"),
    untested("Integrated Terminals"),
    untested("Integrated Tunnels"),
    untested("Interdimensional Wireless Transmitter"),
    untested("Inventory Essentials"),
    untested("In World Recipes"),
    untested("Iron's Arms 'n Artifice"),
    untested("Iron's Gems 'n Jewelry"),
    untested("Iron's Lib"),
    untested("Jade"),
    untested("Jonn's Trophies"),
    untested("Journeymap"),
    untested("Jumpy Boats"),
    untested("Jupiter"),
    untested("Just Dire Things"),
    untested("Just Enough Archaeology"),
    untested("Just Enough Items"),
    untested("Just Enough Professions"),
    untested("Just Enough Recipe Sharing"),
    untested("Konkrete"),
    untested("KubeJS"),
    untested("Laser Bridges"),
    untested("LaserIO"),
    untested("Lithostitched"),
    untested("LogisticsNetworks"),
    untested("Luminax"),
    untested("Macaw's Bridges"),
    untested("Macaw's Doors"),
    untested("Macaw's Fences and Walls"),
    untested("Macaw's Furniture"),
    untested("Macaw's Lights and Lamps"),
    untested("Macaw's Paths and Pavings"),
    untested("Macaw's Roofs"),
    untested("Macaw's Stairs and Balconies"),
    untested("Macaw's Trapdoors"),
    untested("Macaw's Windows"),
    untested("MaxHealthFix"),
    untested("Measurements"),
    untested("Melody"),
    untested("Mining Gadgets"),
    untested("Modular Force Field System"),
    untested("More Dragon Eggs"),
    untested("More Red"),
    untested("MrCrayfish's Furniture Mod: Refurbished"),
    untested("Mystical Agradditions"),
    untested("Mystical Agriculture Tiered Crystals"),
    untested("Mystical Automation"),
    untested("Mystical Customization"),
    untested("NetherPortalFix"),
    untested("No Chat Reports"),
    untested("No More Craters"),
    untested("Occultism"),
    untested("Pipe Connector"),
    untested("Productive Bees"),
    untested("Productive Farming"),
    untested("Productive Metalworks"),
    untested("Productive Trees"),
    untested("QuarryPlus"),
    untested("Railcraft Reborn"),
    untested("Refined Construction Sticks"),
    untested("Refined Fluid Substitution"),
    untested("Refined Storage Curios Integration"),
    untested("Refined Storage JEI Integration"),
    untested("Refined Storage Quartz Arsenal"),
    untested("Refined Types"),
    untested("Regions Unexplored"),
    untested("Reliquary Reincarnations"),
    untested("Rhino"),
    untested("Roots Classic"),
    untested("Scalable Cats Force"),
    untested("Shogi"),
    untested("Silent Gear"),
    untested("Silent Gear Metalworks"),
    untested("Silent Lib"),
    untested("Silent's Gems"),
    untested("Simple Backups"),
    untested("Simple Magnets"),
    untested("Sophisticated Storage In Motion"),
    untested("Spark"),
    untested("Spice of Life: Carrot Edition"),
    untested("Spider Overhaul"),
    untested("Step Crafter"),
    untested("Super Factory Manager"),
    untested("Tectonic"),
    untested("Terralith"),
    untested("The Undergarden"),
    untested("Theurgy"),
    untested("Theurgy KubeJS"),
    untested("Titanium"),
    untested("Tool Belt"),
    untested("Training Dummy"),
    untested("Transmog"),
    untested("TrashSlot"),
    untested("Underground Villages"),
    untested("Underwater Village"),
    untested("Universal Grid"),
    untested("Uranus"),
    untested("Utilitarian"),
    untested("Valhelsia Core"),
    untested("Waystones"),
    untested("Wither Skeleton Tweaks"),
    untested("Wits")
];

export const MODS: Mod[] = [...TESTED, ...UNTESTED].toSorted((a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" }));
export const searchMods = (query: string): Mod[] => MODS.filter((mod) => slugify(mod.name).includes(slugify(query)));
