import { slugify } from "../lib/utils";
import type { Locale } from "./content";

export const STATUSES = ["works", "partial", "broken", "untested"] as const;
export type Status = (typeof STATUSES)[number];
export type Mod = { name: string; status: Status; note?: Record<Locale, string> };
const works = (name: string): Mod => ({ name, status: "works" });
const untested = (name: string): Mod => ({ name, status: "untested" });

const TESTED: Mod[] = [
    works("Advanced AE"),
    works("AE Infinity Booster"),
    works("AE2 Import Export Card"),
    works("AE2 Network Analyzer"),
    works("AE2 Wireless Terminals"),
    works("Aether II"),
    works("Apotheosis"),
    works("Apothic Attributes"),
    works("Apothic Enchanting"),
    works("Apothic Spawners"),
    works("Applied Energistics 2"),
    works("Architectury"),
    works("AttributeFix"),
    works("Balm"),
    works("Cable Tiers"),
    works("Camol"),
    works("Charging Gadgets"),
    works("Chisel"),
    works("Chunk Loaders"),
    works("Classic Pipes"),
    works("Clean Swing"),
    works("Clickable Advancements"),
    works("Cloth Config"),
    works("Clumps"),
    works("Cobblegen Galore"),
    works("Comforts"),
    works("Common Capabilities"),
    works("Configured"),
    works("Construction Sticks"),
    works("Cooking for Blockheads"),
    works("Copper Hopper"),
    works("Crafting on a Stick"),
    works("Crafting Tweaks"),
    works("Crash Utilities"),
    works("CraterLib"),
    works("Cristel Lib"),
    works("Croptopia"),
    works("Crystalix"),
    works("CTM"),
    works("Cucumber"),
    works("Cupboard"),
    works("Curios API"),
    works("Cyclops Core"),
    works("Easy Piglins"),
    works("Easy Villagers"),
    works("Ender IO"),
    works("Entangled"),
    works("EpheroLib"),
    works("Ex Deorum"),
    works("Explorer's Compass"),
    works("Extended AE"),
    works("Extended Crafting"),
    works("FastWorkbench"),
    works("Ferrite Core"),
    works("FTB Chunks"),
    works("FTB Essentials"),
    works("FTB Filter System"),
    works("FTB Library"),
    works("FTB Quests"),
    works("FTB Ranks"),
    works("FTB Teams"),
    works("FTB Ultimine"),
    works("FTB XMod Compat"),
    works("GeckoLib"),
    works("GeOre"),
    works("Glodium"),
    works("GuideME"),
    works("Integrated Crafting"),
    works("Integrated Dynamics"),
    works("Integrated Terminals"),
    works("Integrated Tunnels"),
    works("Iron Furnaces"),
    works("Iron Jetpacks"),
    works("Item Collectors"),
    works("Just Enough Items"),
    works("Just Hammers"),
    works("LootR"),
    works("Mahou Tsukai"),
    works("ModernFix"),
    works("Modonomicon"),
    works("Modular Routers"),
    works("Mystical Agriculture"),
    works("Nature's Compass"),
    works("NeoVitae"),
    works("Oritech"),
    works("Pipez"),
    works("Placebo"),
    works("Powah"),
    works("Pylons"),
    works("Refined Construction Sticks"),
    works("Refined Fluid Substitution"),
    works("Refined Storage"),
    works("Refined Storage Curios Integration"),
    works("Refined Storage JEI Integration"),
    works("Refined Storage Quartz Arsenal"),
    works("Refined Types"),
    works("Sophisticated Backpacks"),
    works("Sophisticated Core"),
    works("Sophisticated Storage"),
    works("Trash Cans")
];

const UNTESTED: Mod[] = [
    untested("Agritech: Evolved"),
    untested("AllTheCompressed"),
    untested("AllTheModium"),
    untested("AllTheOres"),
    untested("AllTheTweaks"),
    untested("Applied Construction Sticks"),
    untested("Aquaculture 2"),
    untested("Artifacts"),
    untested("Atlas API"),
    untested("Auroral"),
    untested("Baubley Heart Canisters"),
    untested("BBL Core"),
    untested("BBL Routers"),
    untested("BBL Strainers"),
    untested("Better Advanced Tooltips"),
    untested("Better Compatibility Checker"),
    untested("Building Gadgets 2"),
    untested("DeepNull Reforged"),
    untested("Deimos"),
    untested("DimStorage"),
    untested("Dungeon Crawl"),
    untested("EdivadLib"),
    untested("Elevator Mod"),
    untested("Enchantment Descriptions"),
    untested("Ender IO Endergy"),
    untested("Energized Power"),
    untested("Energy Meter"),
    untested("Epitaphs"),
    untested("EvilCraft"),
    untested("Extra Disks"),
    untested("Extreme Sound Muffler"),
    untested("FancyMenu"),
    untested("Farming for Blockheads"),
    untested("FastFurnace"),
    untested("Fast Suite"),
    untested("Forbidden Arcanus"),
    untested("Forge Config API Port"),
    untested("FramedBlocks"),
    untested("Framework"),
    untested("Functional Storage"),
    untested("Gateways To Eternity"),
    untested("Generator Galore"),
    untested("Get It Together, Drops!"),
    untested("Ice and Fire Community Edition"),
    untested("imfast"),
    untested("Interdimensional Wireless Transmitter"),
    untested("Inventory Essentials"),
    untested("In World Recipes"),
    untested("Iron's Arms 'n Artifice"),
    untested("Iron's Gems 'n Jewelry"),
    untested("Iron's Lib"),
    untested("Jade"),
    untested("Jonn's Trophies"),
    untested("Journeymap"),
    untested("Jumpy Boats"),
    untested("Jupiter"),
    untested("Just Dire Things"),
    untested("Just Enough Archaeology"),
    untested("Just Enough Professions"),
    untested("Just Enough Recipe Sharing"),
    untested("Konkrete"),
    untested("KubeJS"),
    untested("Laser Bridges"),
    untested("LaserIO"),
    untested("Lithostitched"),
    untested("LogisticsNetworks"),
    untested("Luminax"),
    untested("Macaw's Bridges"),
    untested("Macaw's Doors"),
    untested("Macaw's Fences and Walls"),
    untested("Macaw's Furniture"),
    untested("Macaw's Lights and Lamps"),
    untested("Macaw's Paths and Pavings"),
    untested("Macaw's Roofs"),
    untested("Macaw's Stairs and Balconies"),
    untested("Macaw's Trapdoors"),
    untested("Macaw's Windows"),
    untested("MaxHealthFix"),
    untested("Measurements"),
    untested("Melody"),
    untested("Mining Gadgets"),
    untested("Modular Force Field System"),
    untested("More Dragon Eggs"),
    untested("More Red"),
    untested("MrCrayfish's Furniture Mod: Refurbished"),
    untested("Mystical Agradditions"),
    untested("Mystical Agriculture Tiered Crystals"),
    untested("Mystical Automation"),
    untested("Mystical Customization"),
    untested("NetherPortalFix"),
    untested("No Chat Reports"),
    untested("No More Craters"),
    untested("Occultism"),
    untested("Pipe Connector"),
    untested("Productive Bees"),
    untested("Productive Farming"),
    untested("Productive Metalworks"),
    untested("Productive Trees"),
    untested("QuarryPlus"),
    untested("Railcraft Reborn"),
    untested("Regions Unexplored"),
    untested("Reliquary Reincarnations"),
    untested("Rhino"),
    untested("Roots Classic"),
    untested("Scalable Cats Force"),
    untested("Shogi"),
    untested("Silent Gear"),
    untested("Silent Gear Metalworks"),
    untested("Silent Lib"),
    untested("Silent's Gems"),
    untested("Simple Backups"),
    untested("Simple Magnets"),
    untested("Sophisticated Storage In Motion"),
    untested("Spark"),
    untested("Spice of Life: Carrot Edition"),
    untested("Spider Overhaul"),
    untested("Step Crafter"),
    untested("Super Factory Manager"),
    untested("Tectonic"),
    untested("Terralith"),
    untested("The Undergarden"),
    untested("Theurgy"),
    untested("Theurgy KubeJS"),
    untested("Titanium"),
    untested("Tool Belt"),
    untested("Training Dummy"),
    untested("Transmog"),
    untested("TrashSlot"),
    untested("Underground Villages"),
    untested("Underwater Village"),
    untested("Universal Grid"),
    untested("Uranus"),
    untested("Utilitarian"),
    untested("Valhelsia Core"),
    untested("Waystones"),
    untested("Wither Skeleton Tweaks"),
    untested("Wits")
];

export const MODS: Mod[] = [...TESTED, ...UNTESTED].toSorted((a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" }));
export const searchMods = (query: string): Mod[] => MODS.filter((mod) => slugify(mod.name).includes(slugify(query)));
